server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/mydb
    username: root
    password: my-secret-pw
  flyway:
    location: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        ddl-auto: create

